### ISSUE TITLE
Not working with Linux 4.14.84-v7+

### ISSUE THREAD

**Issue by lhchang** [twteamware/raspberrypi-ptp#2]
Hello, 
I was not able to get PTP to work with the following guide, and was not sure if this issue was related to the previously closed issue. Upon running ethtool, I am not able to see `SOF_TIMESTAMPING_TX_SOFTWARE` and also I noticed ptp4l status is "failed to create a clock". I double checked my .conf files and made sure that the smsc95xx.c file was patched. I've attached the following images to reflect this. Thank you for the help!

![conf1](https://user-images.githubusercontent.com/12725316/49531024-42773600-f86e-11e8-9ce0-23abcf3a7f18.png)
![conf2](https://user-images.githubusercontent.com/12725316/49531030-44d99000-f86e-11e8-89ba-678f6302bba0.png)
![ethtool](https://user-images.githubusercontent.com/12725316/49531033-46a35380-f86e-11e8-9afe-aeb26efe61a0.png)
![kernel](https://user-images.githubusercontent.com/12725316/49531037-486d1700-f86e-11e8-8989-90f464cb3eff.png)
![patch](https://user-images.githubusercontent.com/12725316/49531042-4a36da80-f86e-11e8-9c78-0cdaedd230b7.png)

**Comment by kervel** [comment]
i guess this is due to the newer B+ model which has a lan78xx chip that doesn't advertise tx timestamping yet.

**Comment by kervel** [comment]
i tried to make lan78xx report TX timestamping, and at least it does report it now with the patch below.
[lan78xx_patch.zip](https://github.com/twteamware/raspberrypi-ptp/files/2780780/lan78xx_patch.zip)

i tested it with two raspberries and they actually seem to converge but i need to check if i was just lucky.

**Comment by gizero** [comment]
Hi! Sorry for late reply but notifications for this issue got totally buried by noise :-(
While I haven't had a chance to test ptp on a RPi 3B+, which I don't have available, you are right saying it uses a different ethernet driver (`lan78xx` instead of `smsc95xx`) than model 3B. I'm not an expert in ethernet drivers at all, but as far as I can see, `smsc95xx` does implement software timestamping on both RX and TX paths as well as `smsc95xx`. What's missing once again is the capability to announce such functionality via `ethtool`. Your patch seems to be correct, being the counterpart of commit https://github.com/torvalds/linux/commit/a8f5cb9e79913a6918f87495d4969706f8817b8e in mainline for `smsc95xx`. You'd better try to submit it to mainline for review. linux-raspberry is not accepting patches suitable for mainline and their policy is mainline first. That's the way to go to make it available sooner to RPi people. While at it, would you mind sending a PR to this repo as well with a comment on RPi3B+ need for this patch?

**Comment by kervel** [comment]
hmm today i see these messages in the ptp log on another node

`Jan 22 11:24:43 hostname ptp4l: [3276.669] port 1: received DELAY_REQ without timestamp
`
so i guess its not done yet (strange that i didn't see these messages yesterday)

**Comment by kervel** [comment]
in the mean time i did some more tests and the log messages above did not prevent the time sync from being okay (eg time sync is definately working fine). i'll post a message to the linuxptp-users ml to ask if the warning means broken driver or not.

**Comment by gizero** [comment]
I'm inclined to close this issue because of your last comment. Before that, can you please link back to the above mentioned ml discussion if you managed to start it up?
